Inline a handful of functions from num-integer
chronotope/chrono pull request #1004
Opened 2023-03-30 16:02 UTC by alex

The motivation for this is that we use a very small portion of what num-integer provides, but it's a relatively heavy dependency -- it brings in several crates with build scripts. The goal here is to reduce compilation time for projects using chrono.

Let me know if you'd prefer I rebase this onto the 0.4.x branch.

2023-03-30 22:17 UTC, jtmoon79 requested changes
Removing dependencies is good.

2023-03-30 22:17 UTC, jtmoon79 commented on src/utils.rs
> +// All code cribbed from num-integer. We do this to minimize dependencies and
When cribbing other software, something to be cautious around is declaring licenses. On advice of a lawyer, it was adequate to surround code with explicit comments about the source, and the license*.

Here is an example from my own project https://github.com/jtmoon79/super-speedy-syslog-searcher/blob/0.5.58/src/data/utmpx.rs#L134-L186

I recommend doing the same here. The top of the file should include a docstring stating something like

```lang-rust
//! Number utility functions.
//!
//! Code in this file `src/utils.rs` was copied from project [`num-integer`].
//! That project is [licensed under the MIT license].
//!
//! [`num-integer`]: https://github.com/rust-num/num-integer
//! [licensed under the MIT license]: https://github.com/rust-num/num-integer/blob/num-integer-0.1.45/LICENSE-MIT
```

_* not formal legal advice, just a recommendation_

2023-03-30 22:17 UTC, jtmoon79 commented on src/utils.rs
> +macro_rules! impl_integer_signed {
Could `impl_integer_signed` have a docstring explaining it?

2023-03-30 22:17 UTC, jtmoon79 commented on src/utils.rs
> +macro_rules! impl_integer_unsigned {
Could `impl_integer_unsigned` have a docstring explaining it?

2023-03-30 22:28 UTC, jtmoon79 approved these changes
Thanks for the update. I prefer `///` so those comments also appear in online docs. But code comments are adequate.

2023-03-30 22:30 UTC, alex commented
The module isn't public, so I don't think it'd show up in docs either way?

2023-03-30 22:33 UTC, jtmoon79 commented
> The module isn't public, so I don't think it'd show up in docs either way?

Good point!

2023-03-31 08:25 UTC, djc commented
Oh, good idea. It would be nice to have this on 0.4.x as well, would you mind rebasing?

2023-03-31 11:32 UTC, alex commented
@djc hmm, So 0.4.x has `impl num_traits::FromPrimitive for Month`, which makes it part of the public API. I'm not sure if we can remove it without a compatibility break there?

2023-03-31 11:45 UTC, alex commented
https://github.com/chronotope/chrono/pull/794 is the PR that removed the num-traits usage in the API, FWIW.

2023-03-31 12:58 UTC, djc commented
Ah yeah, that would be the reason we haven't done this on 0.4. Okay, let's just do this on 0.5?

2023-03-31 12:59 UTC, alex commented
Sounds good. I think this is ready for review then (modulo the CI issues that are also present on main.)

2023-04-03 11:18 UTC, djc approved these changes

2023-04-03 11:18 UTC, merged