Fix test_leap_second during DST transition
chronotope/chrono pull request #1064
Opened 2023-05-12 13:48 UTC by pitdicker

This test can fail if it is run on a date and in a timezone that just happens to have a DST transition 1:00 and 2:00 that day.

Fixes https://github.com/chronotope/chrono/issues/866, which the approach described in that issue.

2023-05-13 06:09 UTC, jtmoon79 requested changes
It doesn't seem this PR is fixing the root cause.

2023-05-13 06:09 UTC, jtmoon79 commented on src/offset/local/mod.rs
> +        if let Some(dt) = today.and_hms_milli_opt(1, 2, 59, 1000) {
I was able to reproduce Issue #866 with this test at tag `v0.4.21` and current branch `0.4.x` 6655649e861b717cd1d86193cb0bd5eec3e2cc75
```rust
    /// Test Issue #866
    #[test]
    fn test_issue_866() {
        #[allow(deprecated)]
        let local_20221106 = Local.ymd(2022, 11, 6);
        let _dt_20221106 = local_20221106 .and_hms_milli_opt(1, 2, 59, 1000).unwrap();
    }
```

2023-05-13 19:26 UTC, pitdicker commented
True, this is 'covering up an error'.

Previously, it would always fail once a year if you live in a timezone with a transition between 1:00 and 2:00. Or maybe twice a year, if there is second date with a transition. The `unwrap` is on a `LocalResult` which may not be `Single`.

Instead of always failing, it will now always pass on such a day. Since it will fail the next day, and always fail on CI with multiple timezones, this seems ok to me.

The goal is to test leap seconds are treated sensibly by `Local`. I did not want to make it much more complicated.

2023-05-14 05:04 UTC, pitdicker commented
I have changed the time to test the (fake) leap second to around 15:00. a DST transition should be super rare, compared to a time during the night.

2023-05-15 09:39 UTC, djc approved these changes
This seems reasonable to me.

2023-05-15 09:39 UTC, merged