Add FromStr for FixedOffset
chronotope/chrono pull request #1092
Opened 2023-05-28 07:09 UTC by yshui

Closes #314

2023-05-28 09:07 UTC, pitdicker reviewed
Seems like a sensible addition to me.

2023-05-28 09:07 UTC, pitdicker commented on src/format/scan.rs
> +pub(crate) fn consume_colon_maybe(mut s: &str) -> ParseResult<&str> {
These two methods don't need to be public for the crate.

But maybe you should keep them like this, and put the `FromStr` implementation in `offset/fixed.rs`. It seems to be an exception to put them in this file.

2023-05-28 09:42 UTC, djc reviewed
Makes sense, thanks!

2023-05-28 09:42 UTC, djc commented on src/format/mod.rs
> +/// Parsing a `str` into a `FixedOffset` uses the format [`%z`](./format/strftime/index.html).
Please move this impl below the `FixedOffset` definition.

2023-05-28 23:54 UTC, jtmoon79 requested changes

2023-05-28 23:54 UTC, jtmoon79 commented on src/format/mod.rs
> +/// Parsing a `str` into a `FixedOffset` uses the format [`%z`](./format/strftime/index.html).
This addition should be move to `src/offset/fixed.rs`.

2023-05-28 23:54 UTC, jtmoon79 commented on src/format/mod.rs
> +
This addition should be move to `src/offset/fixed.rs`.

2023-06-29 11:09 UTC, pitdicker commented
Merged in https://github.com/chronotope/chrono/pull/1157. Thank you for working on this.

2023-06-29 11:10 UTC, closed without merging