Add `DateTime::<Utc>::from_timestamp_opt`
chronotope/chrono pull request #1278
Opened 2023-09-09 23:51 UTC by demurgos

This commit adds the new constructor `from_timestamp_opt` to build a `DateTime<Utc>` from a UNIX timestamp.

Figuring out how to convert a timestamp into a `DateTime<Utc>` was a common issue:
- https://github.com/chronotope/chrono/issues/88
- https://github.com/chronotope/chrono/issues/200
- https://github.com/chronotope/chrono/issues/832

This commit should make `DateTime<Utc>` creation more discoverable and intuitive.

This commit respects the current convention of using the `_opt` suffix for fallible functions. As panicking variants on invalid input are deprecated, no panicking variant is provided. See [this issue](https://github.com/chronotope/chrono/issues/815) for discussion about error handling and panics.

Closes https://github.com/chronotope/chrono/issues/832

2023-09-09 23:54 UTC, demurgos commented
The discussion in #832 proposed to add `DateTime::from_timestamp`, but since then there was the update deprecating panicking functions. That's why I only added `from_timestamp_opt`. I expect this to become `from_timestamp` if/once `chrono` error handling is refactored. Until then, `_opt` felt better for consistency.

2023-09-10 05:30 UTC, pitdicker requested changes
Thank you for working on this!

Can you please rebase on 0.4.x? Then it can be included in a 0.4 release, instead of a far-off 0.5.
That should also take care of code coverage with doctests.

2023-09-10 05:30 UTC, pitdicker commented on src/datetime/mod.rs
> +    /// or [`DateTime::with_timezone`].
Good documentation :+1:

2023-09-10 05:30 UTC, pitdicker commented on src/datetime/mod.rs
> +            .map(|ndt| DateTime::from_naive_utc_and_offset(ndt, Utc))
This can be simplified to `NaiveDateTime::from_timestamp_opt(secs, nsecs).map(|ndt| ndt.and_utc())`

2023-09-10 05:30 UTC, pitdicker commented on src/lib.rs
> +//! Use [`DateTime::from_timestamp_opt(seconds, nanoseconds)`](./struct.DateTime.html#method.from_timestamp_opt)
It is pre-existing, but can you replace the html link with:
```
[`DateTime::from_timestamp_opt(seconds, nanoseconds)`](DateTime::from_timestamp_opt)
```

2023-09-10 05:32 UTC, pitdicker commented
> This commit respects the current convention of using the `_opt` suffix for fallible functions.

For new methods I think we just drop the `_opt` suffix.

2023-09-10 07:09 UTC, demurgos commented
Thank you for the quick review, I'll apply the changes and open a new PR for the branch `0.4.x`. I also learned about the `[`DateTime::from_timestamp_opt(seconds, nanoseconds)`](DateTime::from_timestamp_opt)` syntax for links so it's nice :)

2023-09-10 07:21 UTC, demurgos commented
Superseded by the PR for the branch `0.4.x : https://github.com/chronotope/chrono/pull/1278

2023-09-10 07:21 UTC, closed without merging