Serde rfc 2822
chronotope/chrono pull request #1412
Opened 2024-02-04 23:24 UTC by chrisranderson

### Thanks for contributing to chrono!

>If your feature is semver-compatible, please target the main branch;
> for semver-incompatible changes, please target the `0.5.x` branch.

I'm not sure what this means - every change is compatible with semver, right? Are you asking if it's a backwards-incompatible change?

> Please consider adding a test to ensure your bug fix/feature will not break in the future.

Done.

2024-02-04 23:26 UTC, chrisranderson commented
Continuing from @pitdicker https://github.com/chronotope/chrono/issues/1292#issuecomment-1918472102:

> I could comment on a few nits, but it looks pretty much like it should.
I believe all other deserialize implementations deserialize to DateTime<FixedOffset>? We should do so here to. DateTime<Utc> discards the serialized offset info.
And all other (de)serializers support an Option variant.

I changed it to deserialize to `DateTime<FixedOffset>`. Not all other (de)serializers support an Option variant, though - the rfc3339 one doesn't, right?

2024-02-05 09:20 UTC, pitdicker requested changes
We are inevitably going to get a request to add an optional variant. But lets get this ready first.

2024-02-05 09:20 UTC, pitdicker commented on src/datetime/serde.rs
> +pub struct Rfc2822Visitor;
I believe you can make this private. The others are public for backwards compatibility.

2024-02-05 09:20 UTC, pitdicker commented on src/datetime/serde.rs
> +            formatter.write_str("an RFC 2822 (email) formatted datetime string")
Personally I would remove `(email) `.

2024-02-05 09:20 UTC, pitdicker commented on src/datetime/serde.rs
> +        serializer.serialize_str(&dt.to_rfc2822())
In `format/formatting.rs` there is a `write_rfc2822` function that works without allocating. Using that will make this serializer work on `no_std` targets like the others.

You will have to adjust its `#[cfg(feature = "alloc")]` to also enable it with the `serde` feature.

2024-02-05 09:26 UTC, pitdicker commented
Forgot to add: thank you for working on this!

And the changes are related enough to be squashed into one commit please.

2024-03-01 13:38 UTC, pitdicker commented
@chrisranderson are you still interested in completing this PR?

2024-03-01 14:47 UTC, chrisranderson commented
No, sorry. Gratefully, I am now employed. Sorry to leave this hanging loose.

2024-03-01 14:51 UTC, pitdicker commented
Congratulations! And no worries.

2024-03-01 15:40 UTC, pitdicker commented
Opened #1477.

2024-03-01 15:40 UTC, closed without merging