Simplify RFC 2822 comment parser
chronotope/chrono pull request #737
Opened 2022-07-25 11:48 UTC by djc

Tweak the implementation from #733 to simplify the parser.

cc @Finomnis

2022-07-25 12:36 UTC, esheppa commented
Looks good - looks like this disallows training whitespace which is consistent with the behavior pre acd4ecf09fd0e5e35e2b5d5e074f6e1cc77172fc. Only thought I had was changing the test strings to raw strings as the multiple levels of escaping is a bit tricky - I added a PR to this branch to do that, however please feel free to ignore if you think it's not necessary

2022-07-25 12:37 UTC, esheppa approved these changes

2022-07-25 13:51 UTC, Finomnis requested changes
The reworked parser is quite elegant. I don't understand why support for multiple comments was removed, though.

2022-07-25 13:51 UTC, Finomnis commented on src/format/parse.rs
> +        s = s_out;
Why was this changed? Multiple comments are allowed, and whitespace between/around as well.

2022-07-25 13:51 UTC, Finomnis commented on src/format/parse.rs
> +            r"Tue, 20 Jan 2015 17:35:20 -0800 ( (UTC ) (\( (a)\(( \t ) ) \\( \) ))",
Based on my other comment, we should probably add a test here for multiple comments

2022-07-25 13:57 UTC, Finomnis requested changes

2022-07-25 13:57 UTC, Finomnis commented on src/format/parse.rs
> +        s = s_out;
OK I saw now that you added the whitespace into the comment parser.

2022-07-25 13:57 UTC, Finomnis commented on src/format/scan.rs
> +            (Start, b' ') => Start,
According to the RFC, whitespace consists of more than just spaces, it can be space, tab, \r, \n, etc.

2022-07-25 14:01 UTC, Finomnis commented on src/format/scan.rs
> +        (r"(\\)", Ok("")),
Missing additional tests for the newly introduced whitespace parsing.

2022-07-25 14:32 UTC, Finomnis commented
Created PR with fixes for my comments: https://github.com/chronotope/chrono/pull/739

2022-07-25 16:02 UTC, Finomnis approved these changes

2022-07-25 22:45 UTC, esheppa approved these changes

2022-07-26 07:59 UTC, merged

2022-07-26 07:59 UTC, djc commented
Thanks, great collaboration here!