convenience functions to create NaiveDates
chronotope/chrono pull request #893
Opened 2022-11-23 22:32 UTC by esheppa

These functions are to reduce the number of unwraps needed when creating NaiveDates

2023-04-05 22:23 UTC, jtmoon79 requested changes
These look convenient! 

Please add `#[must_use]` to these functions.

2023-04-28 09:54 UTC, pitdicker commented
I am not super convinced of the usefulness of all these methods. My reason is that there are all kinds of operations someone may want to do on dates. Where do you draw the line?

`end_month` and `end_year` seem useful because it they are non-trivial. You should get the current year/month, add 1 (this can cause a panic on overflow), and get the preceding day.

But then you would also want `start_month` and `start_year` for symmetry, which don't feel valuable enough for me.

Would similar methods on `NaiveDateTime` or `DateTime` make sense? Would the end of a month be at the last second? Or the last nanoseond? Or maybe even leap-second? Strictly speaking, the end is the same as the start of the next day, at 0:00:00. But than the date would be different from the one returned by `NaiveDate::end_month`.

2023-05-07 06:49 UTC, pitdicker commented on src/naive/date.rs
> +    /// Create a `NaiveDate` of the ;ast day of the given year and month
```suggestion
    /// Create a `NaiveDate` of the last day of the given year and month
```

2023-05-07 06:49 UTC, pitdicker commented on src/naive/date.rs
> +    pub fn start_year(year: i16) -> NaiveDate {
Using an `i16` ties into your work in https://github.com/chronotope/chrono/pull/882. But maybe it is best to accept an `i32` until the decision is made to restrict the range of allowed years?

2023-05-07 06:49 UTC, pitdicker commented on src/naive/date.rs
> +        Self::from_ymd_opt(i32::from(year) + 1, 1, 1).unwrap().pred_opt().unwrap()
This might fail if `year == MAX_YEAR`.

2023-05-07 06:49 UTC, pitdicker commented on src/naive/date.rs
> +        (start + Months::new(1)).pred_opt().unwrap()
This might fail if `year == MAX_YEAR && month == 12`.

2024-04-10 12:32 UTC, pitdicker commented
Closing. I would be interested to have a method to easily create a `NaiveDate` at the end of a month.

2024-04-10 12:32 UTC, closed without merging