Add support for parsing JSON timestamps from strings.
chronotope/chrono pull request #926
Opened 2022-12-30 01:39 UTC by rayhaanj

This change adds support for parsing string as (numeric) timestamps.

I had a look at the tests but was not sure where I should put the test for this feature, as the current logic to run tests is calling `datetime::test_decodable_json` which does not seem to be exercising the visitor path? Let me know where I should put them and I'll add the tests.

2023-01-09 13:53 UTC, djc approved these changes
Makes sense, thanks!

2023-02-16 12:37 UTC, esheppa commented
I think it's probably worthwhile having a few tests to verify this works. They could just be placed at the bottom of the `serde.rs` file along with the other tests there.

2023-04-05 19:24 UTC, jtmoon79 requested changes
Needs test cases.

@rayhaanj is it possible to add test cases for "before"?  That is, test cases that exercise some serde code before your changes. Then another commit with your changes + new test cases (or test case changes).

2024-04-06 18:17 UTC, pitdicker commented
I'll try to help get this PR ready.
Added some very basic doctests. Good this was requested in previous reviews, as it didn't work yet :smile:.
We now need to use `deserialize_any` instead of `deserialize_i64`.

2024-04-06 18:47 UTC, pitdicker commented
Hmm, [`desertialize_any`](https://docs.rs/serde/latest/serde/de/trait.Deserializer.html#tymethod.deserialize_any) may not be the best thing to reach for:
> Require the `Deserializer` to figure out how to drive the visitor based on what data type is in the input.
>
> When implementing `Deserialize`, you should avoid relying on `Deserializer::deserialize_any` unless you need to be told by the `Deserializer` what type is in the input. Know that relying on `Deserializer::deserialize_any` means your data type will be able to deserialize from self-describing formats only, ruling out Postcard and many others.

2024-04-06 19:51 UTC, djc commented
Yeah, I don't think we should restrict to self-describing formats only.

2024-04-06 20:02 UTC, pitdicker commented
I've opened a question in the serde repo just in case. I think this is not going to work out, but no need to hurry closing this PR yet :smile:.

2024-04-10 12:24 UTC, closed without merging