move MIN_UTC, MAX_UTC to a specialized impl
chronotope/chrono pull request #935
Opened 2023-01-09 16:15 UTC by petar-dambovaliev

For more info visit the [issue](https://github.com/chronotope/chrono/issues/932)

2023-01-09 16:34 UTC, djc commented
So how does this change how they can be referenced? Did you test that it changes? It's not at all obvious to me.

2023-01-09 17:15 UTC, petar-dambovaliev commented
> So how does this change how they can be referenced? Did you test that it changes? It's not at all obvious to me.

I tested it out.
Previously, you had to write
```
let mut min: DateTime<Utc> = DateTime::MAX_UTC;
```
Now, it works as
```
let mut min = DateTime::MAX_UTC;
```
The generic argument has been inferred.

2023-01-10 10:55 UTC, djc commented
Yes, adding some tests would be useful.

2023-01-10 11:17 UTC, petar-dambovaliev commented
> Yes, adding some tests would be useful. As an alternative option, if we name these `MAX` and `MIN` (losing the `_UTC`) suffix this would be a compatible change which can go into 0.4.x.

Yes, removing the postfix makes sense.
Do you mean leaving the original constants where they were and adding these 2 new ones?

2023-01-10 12:31 UTC, djc commented
> > Yes, adding some tests would be useful. As an alternative option, if we name these `MAX` and `MIN` (losing the `_UTC`) suffix this would be a compatible change which can go into 0.4.x.
> 
> Yes, removing the postfix makes sense. Do you mean leaving the original constants where they were and adding these 2 new ones?

Yes. You'll likely also want to rebase your change on the 0.4.x branch (and change the target branch for the PR).

2023-01-10 12:40 UTC, petar-dambovaliev commented
> > > Yes, adding some tests would be useful. As an alternative option, if we name these `MAX` and `MIN` (losing the `_UTC`) suffix this would be a compatible change which can go into 0.4.x.
> > 
> > 
> > Yes, removing the postfix makes sense. Do you mean leaving the original constants where they were and adding these 2 new ones?
> 
> Yes. You'll likely also want to rebase your change on the 0.4.x branch (and change the target branch for the PR).

Okay, cool.

2023-04-05 19:21 UTC, jtmoon79 requested changes
Needs test cases that enforce compile-time expectations.

For example,
```lang-rust
fn test_min_utc() {
     let m: DateTime<Utc> = DateTime::MIN_UTC;
}
```
(IIUC the code)

Ideally, this would be two commits:
1. a commit that adds test cases
2. a commit that adds code changes + (if necessary) test case adjustments

2023-09-19 14:04 UTC, pitdicker commented
This is in theory a semver-breaking change, but only for some *very* strange code:
```rust
let dt: DateTime<Utc> = DateTime::<FixedOffset>::MAX_UTC;
```
I.e. you currently have to supply some generic parameter, but then it would just be ignored and the return type is `DateTime<Utc>`.

But a GitHub search shows people are actually writing something like this. For example [1](https://github.com/gunosy/redash-searcher/blob/14074c4ebf850189b9803447c5248c06d2c9c927/redash-searcher-sync/src/app.rs#L215), [2](https://github.com/stagrim/Asta/blob/9302700fd1cdf62def760b8fabd142901f79a338/sasta/src/store/schedule.rs#L170), [3](https://github.com/princeofnubia/dozer/blob/cf49da5510e7d944f9c5f0d8dbc222aea37c1d8e/dozer-sql/src/pipeline/aggregation/min.rs#L135).

What it does show is that this issue is worth fixing.

@djc shall I rebase this on main?

2023-09-21 08:44 UTC, pitdicker commented
Merged via https://github.com/chronotope/chrono/pull/1303. @petar-dambovaliev Thanks for working on this!

2023-09-21 08:44 UTC, closed without merging