Fix panic in DateTime::checked_add_days
chronotope/chrono pull request #941
Opened 2023-01-22 19:02 UTC by Ekleog

Incidentally, add TimeDelta::try_* builders so that it's possible to build them without risking a panic.

This issue was found thanks to cargo-bolero-fuzzing my web server, without actually trying to fuzz chrono itself.

2023-01-23 08:48 UTC, djc commented
Going to close this. We'll review (and probably merge) #942 (the 0.4.x version of this change) and then eventually that change will make it to the main branch as part of a regular merge of 0.4.x work into main.

2023-01-23 19:05 UTC, djc commented
Ahh, sorry, had missed that context. Will open this back up, then we can review it after the other change has made its way into main.

2023-01-28 19:20 UTC, Ekleog commented
Awesome thanks! :)

2023-03-17 10:45 UTC, djc commented
(Merge is pending in #986.)

2023-03-17 11:14 UTC, djc commented
Can you rebase this onto main? Should hopefully not be too painful.

2023-03-18 11:43 UTC, esheppa reviewed
Looks good to me, pending rebase

2023-04-05 19:17 UTC, jtmoon79 requested changes
Can you add test cases for the before and after for all changed functions?
e.g. `test_diff_days`, `test_weeks`, `test_try_weeks`, etc.

Specifically, two commits
1. a commit with new test cases
2. a commit of these changes + adjustments to those test cases (if needed)

2023-05-13 13:20 UTC, Ekleog commented
Sorry for the delay. I have basically not done any non-work software development for a few months, and have a few personal projects that will be higher priority for me than this PR, so I don't think I'll actually come back to this anytime soon.

Do you prefer if I leave the PR open so that someone else can easily notice it and take it over (and so that it tracks the fact that the panic is currently reachable on `main`), or should I just close it?

2023-05-14 07:07 UTC, pitdicker commented
@Ekleog That is very reasonable. If it is ok with you I can take over in a couple of days.

2023-07-17 13:41 UTC, pitdicker commented
The new methods are included in https://github.com/chronotope/chrono/pull/1137 together with other features for `Duration`. They are not yet merged however.

2023-07-17 13:41 UTC, closed without merging